### ISSUE TITLE
Error: caught exception: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by jfcarrano** [edsu/waybackprov#1]
I get an error when I try to use waybackprov. For each url I try (including urls known to be in the Internet Archive) I receive the response "ERROR - caught exception: the JSON object must be str, not 'bytes'". I've tried installing both with pip and pip3 and am using python 3.5.2. I'm using python in Ubuntu 16.04 on the Linux subsystem on Windows 10.

**Comment by edsu** [comment]
A fix for this was just released as part of v0.0.7. You should be able to update with:

    pip install --upgrade waybackprov

Thanks for taking the time to test it out, and report the problem. It didn't manifest on OSX but it did on Ubuntu. Perhaps it was a locale issue... I debated having waybackprov rely on the requests library for the HTTP interactions, since it handles all these edge cases so well, but held off for now.  If another problem like this pops up I'll move it over.

**Comment by jfcarrano** [comment]
Thanks! Seems to be working for me now
